'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aluno
    Public Property Matricula As String
    Public Property Nome As String
    Public Property Projeto As String
    Public Property Recebe_bolsa As Nullable(Of Boolean)
    Public Property Professor As String

    Public Overridable Property Professor1 As Professor
    Public Overridable Property Projeto1 As Projeto

End Class
