'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class IFA_A6LP2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=IFA_A6LP2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Alunoes() As DbSet(Of Aluno)
    Public Overridable Property Professors() As DbSet(Of Professor)
    Public Overridable Property Projetoes() As DbSet(Of Projeto)

End Class
